/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/scene.glb 
*/

import React, { useRef, useEffect } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useAnimationContext } from "./AnimationContext";

export const Cube = (props) => {
  const group = useRef();
  const { nodes, animations } = useGLTF("/scene.glb");
  const { actions, names } = useAnimations(animations, group);
  const { animationName } = useAnimationContext();

  useEffect(() => {
    actions[animationName]?.reset().fadeIn(0.5).play();
    return () => {
      actions[animationName]?.fadeOut(0.5);
    };
  }, [actions, names, animationName]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Cube" geometry={nodes.Cube.geometry}>
          <meshNormalMaterial />
        </mesh>
      </group>
    </group>
  );
};

useGLTF.preload("/scene.glb");
